'use client';
import { FormEvent, useState } from 'react';
import { supabaseBrowser } from '../lib/supabase';

const events=[['Hancy Weekly Cup','5v5 • Knockout','NPR 100','NPR 2,000'],['Night Battle','5v5 • Best of 1','NPR 50','NPR 1,000'],['Hancy Championship','5v5 • Best of 3','NPR 250','NPR 5,000']];

export default function Home(){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 async function signup(e:FormEvent){e.preventDefault();setMsg('');setBusy(true);const sb=supabaseBrowser();if(!sb){setMsg('Supabase keys missing. Add them to .env.local');setBusy(false);return;}const {error}=await sb.auth.signUp({email,password});setMsg(error?error.message:'Account created! Check your email if confirmation is enabled.');setBusy(false)}
 return <><header><div className="wrap nav"><div className="logo">HANCY<span>ARENA</span></div><div className="links"><a href="#home">Home</a><a href="#tournaments">Tournaments</a><a href="#leaderboard">Leaderboard</a><a href="#login">Login</a></div></div></header>
 <main id="home"><div className="wrap"><section className="hero"><div><span className="badge">⚡ REAL MLBB TOURNAMENT PLATFORM</span><h1>Play. Compete.<br/><span>Win.</span></h1><p>Hancy Arena is your place to join Mobile Legends tournaments, register your squad and track competition results.</p><a className="btn" href="#tournaments">Join Tournament</a><a className="btn alt" href="#login">Create Account</a></div><div className="panel"><div className="trophy">🏆</div><h2 style={{textAlign:'center'}}>HANCY ARENA</h2><p className="muted" style={{textAlign:'center'}}>Tournament platform ready for Supabase.</p></div></section>
 <section className="section"><div className="stats"><div className="panel stat"><strong>24+</strong><span className="muted">Teams</span></div><div className="panel stat"><strong>08</strong><span className="muted">Events</span></div><div className="panel stat"><strong>NPR 50K+</strong><span className="muted">Prize Pool</span></div><div className="panel stat"><strong>4.9★</strong><span className="muted">Rating</span></div></div></section>
 <section className="section" id="tournaments"><h2>🔥 Featured Tournaments</h2><p className="muted">Tournament cards are ready for database integration.</p><div className="grid">{events.map(x=><div className="panel card" key={x[0]}><span className="status">OPEN</span><h3>{x[0]}</h3><p className="muted">{x[1]}</p><b>Entry: {x[2]}</b><p className="muted">Prize Pool: {x[3]}</p><a className="btn" href="#login">Register</a></div>)}</div></section>
 <section className="section" id="leaderboard"><h2>🏆 Leaderboard</h2><div className="panel"><table className="table"><thead><tr><th>#</th><th>Team</th><th>Wins</th><th>Points</th></tr></thead><tbody><tr><td>1</td><td>Hancy Warriors</td><td>8</td><td>240</td></tr><tr><td>2</td><td>Shadow Five</td><td>7</td><td>210</td></tr><tr><td>3</td><td>Nova Squad</td><td>6</td><td>185</td></tr></tbody></table></div></section>
 <section className="section" id="login"><h2>🔐 Create Account</h2><p className="muted">This form uses Supabase Auth when your keys are configured.</p><div className="panel"><form className="form" onSubmit={signup}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password (minimum 6 characters)" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/><button className="btn" disabled={busy}>{busy?'Creating...':'Create Account'}</button>{msg&&<div className={msg.toLowerCase().includes('error')||msg.toLowerCase().includes('missing')?'msg err':'msg'}>{msg}</div>}</form></div></section></div></main><footer>© 2026 Hancy Arena • MLBB Tournament Platform</footer></>;
}
